name: Create Medusa Admin

on:
  workflow_dispatch:

jobs:
  create-admin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run create-admin.js
        run: node scripts/create-admin.js
